services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "9000:9000"
    environment:
      - ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - LOG_DIR=/app/logs
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
