services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app-z0s008wk08cog88c4s40o8s4-101101036388
    ports:
      - "9000:9000"
    volumes:
      - "sqlite_data:/app/db"
    environment:
      ENV: production
      COOLIFY_BRANCH: '"main"'
      COOLIFY_CONTAINER_NAME: '"fastapi_app-z0s008wk08cog88c4s40o8s4-101101036388"'
      COOLIFY_URL: "https://api.pkfalumni.com"
      COOLIFY_FQDN: api.pkfalumni.com
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.379
      - coolify.applicationId=19
      - coolify.type=application
      - coolify.name=fastapi_app-z0s008wk08cog88c4s40o8s4-101101036388
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-z0s008wk08cog88c4s40o8s4-fastapi_app.entryPoints=http
      - traefik.http.routers.http-0-z0s008wk08cog88c4s40o8s4-fastapi_app.middlewares=redirect-to-https
      - "traefik.http.routers.http-0-z0s008wk08cog88c4s40o8s4-fastapi_app.rule=Host(`api.pkfalumni.com`) && PathPrefix(`/`)"
      - traefik.http.routers.https-0-z0s008wk08cog88c4s40o8s4-fastapi_app.entryPoints=https
      - traefik.http.routers.https-0-z0s008wk08cog88c4s40o8s4-fastapi_app.middlewares=gzip
      - "traefik.http.routers.https-0-z0s008wk08cog88c4s40o8s4-fastapi_app.rule=Host(`api.pkfalumni.com`) && PathPrefix(`/`)"
      - traefik.http.routers.https-0-z0s008wk08cog88c4s40o8s4-fastapi_app.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-z0s008wk08cog88c4s40o8s4-fastapi_app.tls=true
      - "caddy_0.encode=zstd gzip"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams}}"
      - "caddy_0.handle_path=/*"
      - caddy_0.header=-Server
      - "caddy_0.try_files={path} /index.html /index.php"
      - "caddy_0=https://api.pkfalumni.com"
      - caddy_ingress_network=z0s008wk08cog88c4s40o8s4
    networks:
      z0s008wk08cog88c4s40o8s4: null
volumes:
  sqlite_data:
networks:
  z0s008wk08cog88c4s40o8s4:
    name: z0s008wk08cog88c4s40o8s4
    external: true
configs: {}
secrets: {}
