services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "9000:9000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pkfalumni
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
