services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "9000:9000"
    volumes:
      - sqlite_data:/app/sql_database
    environment:
      - ENV=production

volumes:
  sqlite_data:
