services:
  db:
    image: postgres:15
    container_name: pkfalumni_db_dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pkfalumni_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi_app_dev
    ports:
      - "9000:9000"
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pkfalumni_dev
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data_dev:
