"""User journey middleware

Revision ID: 4f47bd17c705
Revises: faccf920de79
Create Date: 2025-11-10 23:12:15.441030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f47bd17c705'
down_revision: Union[str, None] = 'faccf920de79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_journeys_action'), 'user_journeys', ['action'], unique=False)
    op.create_index(op.f('ix_user_journeys_id'), 'user_journeys', ['id'], unique=False)
    op.create_index(op.f('ix_user_journeys_session_token'), 'user_journeys', ['session_token'], unique=False)
    op.create_index(op.f('ix_user_journeys_timestamp'), 'user_journeys', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_journeys_user_id'), 'user_journeys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_journeys_user_id'), table_name='user_journeys')
    op.drop_index(op.f('ix_user_journeys_timestamp'), table_name='user_journeys')
    op.drop_index(op.f('ix_user_journeys_session_token'), table_name='user_journeys')
    op.drop_index(op.f('ix_user_journeys_id'), table_name='user_journeys')
    op.drop_index(op.f('ix_user_journeys_action'), table_name='user_journeys')
    op.drop_table('user_journeys')
    # ### end Alembic commands ###
