"""Switch mentor_email to mentor_id

Revision ID: 7dc36ecb2bc8
Revises: 
Create Date: 2025-05-23 04:15:14.317278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc36ecb2bc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_unique_constraint(None, 'announcements', ['title'])
    op.add_column('users', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.Enum('admin', 'user', name='userrole'),
               existing_nullable=False)
    op.drop_constraint('unique_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['mentor_id'], ['id'])
    op.drop_column('users', 'mentor_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mentor_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('unique_email', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'mentor_id')
    op.drop_constraint(None, 'announcements', type_='unique')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    # ### end Alembic commands ###
