"""Add attachments to posts and comments

Revision ID: 81d1bcd3be5c
Revises: db3e76a05172
Create Date: 2025-10-26 14:25:01.212383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d1bcd3be5c'
down_revision: Union[str, None] = 'db3e76a05172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Create the enum type first
    attachment_type_enum = sa.Enum('IMAGE', 'GIPHY', name='attachmenttype')
    attachment_type_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('comments', sa.Column('attachment_type', attachment_type_enum, nullable=True))
    op.add_column('posts', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('attachment_type', attachment_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'attachment_type')
    op.drop_column('posts', 'attachment_url')
    op.drop_column('comments', 'attachment_type')
    op.drop_column('comments', 'attachment_url')
    attachment_type_enum = sa.Enum('IMAGE', 'GIPHY', name='attachmenttype')
    attachment_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
