"""empty message

Revision ID: d5bf746d5453
Revises: 
Create Date: 2025-05-12 22:41:50.617680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bf746d5453'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.create_foreign_key(None, 'user_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_events', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.create_foreign_key(None, 'user_events', 'users', ['user_email'], ['email'])
    op.create_foreign_key(None, 'user_events', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
