"""Add is_active for events

Revision ID: eb5c4f0e4cec
Revises: 7dc36ecb2bc8
Create Date: 2025-07-21 14:03:56.505334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5c4f0e4cec'
down_revision: Union[str, None] = '7dc36ecb2bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
