name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ruff:
    name: ✨ Ruff Lint & Auto-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check
        run: ruff check .

      - name: Run Ruff format (and apply fixes)
        run: ruff format .

      - name: Commit and push formatting changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "🤖 Auto-format code with Ruff"
            git push
          else
            echo "No formatting changes to commit."
