name: Lint

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  ruff:
    name: Ruff Lint & Auto-format (on PR)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check
        run: ruff check .

      - name: Format code with Ruff
        run: ruff format .

      - name: Commit and push formatting changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "Auto-format code with Ruff"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No formatting changes to commit."
          fi
