# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Lint and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install psycopg2-binary

    - name: Run Ruff (lint & auto-fix)
      run: |
        ruff check . --fix --exit-zero

    - name: Format with Black
      run: |
        black .

    - name: Lint with Pylint
      run: |
        find . -name "*.py" | xargs pylint --exit-zero

    - name: Run tests with Pytest
      env:
        TEST_DATABASE_URL: postgresql://user:password@localhost:5432/test_db
      run: |
        pytest
